In [1]:
import numpy as np

# 생성
a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.linspace(0, 1, 5)

# 형태/차원/타입 확인
print(a.shape, a.ndim, a.dtype)
print(b.shape, b.ndim, b.dtype)
print(c.shape, c.ndim, c.dtype)

# reshape
d = np.arange(12) # [0..11]
M = d.reshape(3, -1)
print(M, M.shape)

# dtype 변환
x = np.array([1.2, 2.8, 3.0])
xi = x.astype(np.int32)
print(x, xi, xi.dtype)

(3,) 1 int64
(2, 3) 2 float64
(5,) 1 float64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[1.2 2.8 3. ] [1 2 3] int32


In [ ]:
import numpy as np

A = np.arange(12).reshape(3, 4)
print(A)

# slicing (view)
sub = A[:2, 1:3] # 2x2 : 0~1 rows, 1~2 cols
print("After Slicing", sub, sep='\n')
sub[:] = -1
print(A)

# bollean mask => 조건 결합(&, |, ~) 사용 가능
mask = (A % 2 ==0) & (A > 0)
print("Boolean Masking", mask, sep='\n')
print(A[mask]) # 조건식에 해당하는 원소만 추출

# fancy indexing (copy)
rows = [0, 2] # 범위 아닌 선택
cols = [1, 3] # 따라서, 0행과 2행 + 1열과 3열
picked = A[np.ix_(rows, cols)]
print("Picking", picked, sep='\n')
picked[0, 0] = 999
print("Change value of Picked[0, 0]", picked, A, sep='\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After Slicing
[[1 2]
 [5 6]]
[[ 0 -1 -1  3]
 [ 4 -1 -1  7]
 [ 8  9 10 11]]
Boolean Masking
[[False False False False]
 [ True False False False]
 [ True False  True False]]
[ 4  8 10]
Picking
[[-1  3]
 [ 9 11]]
Change value of Picked[0, 0]
[[999   3]
 [  9  11]]
[[ 0 -1 -1  3]
 [ 4 -1 -1  7]
 [ 8  9 10 11]]


In [22]:
# slicing, masking, indexing practice
import numpy as np

M = np.arange(1, 13).reshape(3, 4)
print("Slicing", M, sep='\n')

sub1 = M[:2, :3]
sub2 = M[:, -1:]
sub3 = M[:, 1::2]
print(sub1, sub2, sub3, sep='\n')

sub1[:] = -1
print("Changed: sub1 to -1", M, sep='\n')

A = np.arange(-6, 7) # -6 ~ 6
print("Masking", A, sep='\n')

mask1 = A > 0
mask2 = A % 2 == 0
mask3 = (A > 0) & (A < 5)
mask4 = (A % 2 == 0) & (A > 0)
print(A[mask1], A[mask2], A[mask3], A[mask4], sep='\n')

B = np.arange(1, 17).reshape(4,4)
print("Indexing", B, sep='\n')

rows = [0, 2]
cols = [1, 3]
picked = B[np.ix_(rows, cols)]
print(picked)
picked[:] = -1
print("Changed: picked to -1", B, sep='\n')


Slicing
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]
[[ 4]
 [ 8]
 [12]]
[[ 2  4]
 [ 6  8]
 [10 12]]
Changed: sub1 to -1
[[-1 -1 -1  4]
 [-1 -1 -1  8]
 [ 9 10 11 12]]
Masking
[-6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6]
[1 2 3 4 5 6]
[-6 -4 -2  0  2  4  6]
[1 2 3 4]
[2 4 6]
Indexing
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  4]
 [10 12]]
Changed: picked to -1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
import numpy as np

# Broadcasting
row = np.arange(1,4).reshape(1,3)
col = np.arange(10, 40, 10).reshape(3,1)
M = row + col
print("Broadcasting", row, col, M, sep='\n') # 같은 값을 복사해서 맞춤

# Vectorization
X = np.arange(10)
Y = X * 2 # X 각 요소에 2 곱함

print("Vectorization", Y, sep='\n')

Broadcasting
[[1 2 3]]
[[10]
 [20]
 [30]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
Vectorization
[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# 데이터는 분포를 가진다
import numpy as np

np.random.seed(42)
n = 1000

heights = np.random.normal(loc=170, scale=6, size=n) # cm
weights = np.random.normal(loc=65, scale=8, size=n) # kg

print("평균 height:", heights.mean())
print("heights의 표준편차:", heights.std())
print("heights의 중앙값:", np.median(heights))
print("heights 백분위수(25%, 75%):", np.percentile(heights, [25, 75]))

# 상관계수(correlation coefficient) 맛보기
corr = np.corrcoef(heights, weights)[0, 1]
print("corr(heights, weights) ≈", round(corr, 3)) # round: 반올림

평균 height: 170.11599233493396
heights의 표준편차: 5.8723572464841265
heights의 중앙값: 170.15180367340935
heights 백분위수(25%, 75%): [166.11445817 173.88766325]
corr(heights, weights) ≈ -0.04


In [22]:
# 단층 퍼셉트론 forward
import numpy as np

# XOR 입력 데이터셋 (4샘플, 2특징)
X = np.array([
  [0, 0],
  [0, 1],
  [1, 0],
  [1, 1]
], dtype=np.float32) # (4,2)

# 임의 가중치/편향
np.random.seed(0)
W = np.random.randn(2) # (2,)
b = 0.1

z = X @ W + b # (4,)
print(z) # 선형결합 값

"""
z를 Step이나 Sigmoid에 넣어서 0/1로 변환
ex) y_pred = (z > 0.5).astype(int)
결과가 정답 y = [0, 1, 1, 0]과 일치해야 "풀린 것"

XOR은 단층 퍼셉트론에서 어떤 W, b를 넣어도 [0,1,1,0] 불가능
=> 선형 분리 불가능 (직선 하나로 0과 1로 나눌 수 없음)
**(0,0), (1,1) : 0
  (0,1), (1,0) : 1

>> 다층 퍼셉트론의 필요성
"""

[0.1        0.50015721 1.86405235 2.26420955]


'\nz를 Step이나 Sigmoid에 넣어서 0/1로 변환\nex) y_pred = (z > 0.5).astype(int)\n결과가 정답 y = [0, 1, 1, 0]과 일치해야 "풀린 것"\n\nXOR은 단층 퍼셉트론에서 어떤 W, b를 넣어도 [0,1,1,0] 불가능\n=> 선형 분리 불가능 (직선 하나로 0과 1로 나눌 수 없음)\n**(0,0), (1,1) : 0\n  (0,1), (1,0) : 1\n\n>> 다층 퍼셉트론의 필요성\n'

In [ ]:
"""
미니배치 퍼셉트론
데이터셋 전체를 한 번에 전부 학습시키기 힘듦 -> 나눠서 처리 (배치,batch)
=> 미니배치(mini-batch) : 보통 32, 64, 128

데이터셋 X.shape = (n, d) (n개 샘플, d차원)
가중치 W.shape = (d,)
편향 b (스칼라 또는 shape 호환)
Forward 계산:
  z = X @ W + b => 결과는 (n,)
"""

import numpy as np

np.random.seed(1) # 시드 고정
n, d = 100, 3 # 샘플 100개, 특징 3개

X = np.random.randn(n, d)
W = np.random.randn(d)
b = np.random.randn() # scalar

z = X @ W + b # <- 벡터화 + 브로드캐스팅

# 간단 검증
assert z.ndim == 1 and z.shape[0] == X.shape[0]

print(z.shape, z[:5], sep='\n')

(100,)
[ 3.81343099 -2.45957597  3.57882295 -1.83644206 -1.92284099]
